---

- name: Create a {{ application_name }} virtual machine via vagrant (env={{ env }})
  hosts: all
  sudo: yes
  sudo_user: root
  remote_user: root
  vars:
    - setup_git_repo: yes
    - update_apt_cache: yes
  vars_files:
    - env_vars/base.yml
    - env_vars/{{ env }}.yml
    - env_vars/{{ env }}_private.yml

  roles:
    - base
    - db
    - rabbitmq
    - web
    - celery
