---

- name: Install Nginx
  apt: name=nginx update_cache={{ update_apt_cache }} state=installed
  tags: packages

- name: Create the symlink for the SSL certificate
  file: src="/etc/letsencrypt/live/{{ inventory_hostname }}/fullchain.pem" dest={{ ssl_dest_dir }}/{{ application_name }}.crt state=link force=yes
  notify: restart nginx

- name: Create the symlink for the SSL private key
  file: src="/etc/letsencrypt/live/{{ inventory_hostname }}/privkey.pem" dest={{ ssl_dest_dir }}/{{ application_name }}.key state=link force=yes
  notify: restart nginx

- name: Create the Nginx configuration file
  template: src=nginx_site_config.j2
            dest=/etc/nginx/sites-available/{{ application_name }}
            backup=yes
  notify: reload nginx

- name: Ensure that the default site is disabled
  command: rm /etc/nginx/sites-enabled/default
           removes=/etc/nginx/sites-enabled/default
  notify: reload nginx

- name: Ensure that the application site is enabled
  command: ln -s /etc/nginx/sites-available/{{ application_name }}
           /etc/nginx/sites-enabled/{{ application_name }}
           creates=/etc/nginx/sites-enabled/{{ application_name }}
  notify: reload nginx

- name: Ensure Nginx service is started
  service: name=nginx state=started enabled=yes
