---

- name: Create the folder for Let's Encrypt
  file: path=/etc/letsencrypt
        state=directory

- name: Create Let's Encrypt config file
  template: src=letsencrypt_config.j2
            dest=/etc/letsencrypt/cli.ini
            backup=yes

- name: Create Let's Encrypt updater script
  template: src=renew_letsencrypt.j2
            dest=/usr/local/bin/renew-letsencrypt
            mode=0755
            backup=yes

- name: Create Let's Encrypt cron job
  cron: name="Renew SSL certificates using Let's Encrypt"
        special_time=monthly
        job=/usr/local/bin/renew-letsencrypt
        backup=yes

- name: "Create 'update_wiki_images' cron job"
  cron: name=update_wiki_images
        special_time=monthly
        job="cd {{ project_path }} && . {{ virtualenv_path }}/bin/activate && . {{ virtualenv_path }}/bin/postactivate && ./manage.py update_wiki_images"
        user={{ application_name }}
        backup=yes
